In [1]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

# Obj file clustering

In [22]:
path = '../../ShapeNet/plant.OBJ'
#path = '../data/processed/meshed/cropped_mesh.ply'

mesh = o3d.io.read_triangle_mesh(path)

In [23]:
o3d.visualization.draw_geometries([mesh], window_name='t')

In [8]:

# clustering methods
def dbscan(point_cloud, eps, mp, debug=False):
    # TODO Gridsearch for param

    with o3d.utility.VerbosityContextManager(
            o3d.utility.VerbosityLevel.Debug) as cm:
        labels = np.array(
            point_cloud.cluster_dbscan(eps=eps, min_points=mp, print_progress=True))

    max_label = labels.max()
    print(f"point cloud has {max_label + 1} clusters")
    colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
    colors[labels < 0] = 0
    point_cloud.colors = o3d.utility.Vector3dVector(colors[:, :3])

    return point_cloud

In [76]:
pc = mesh.sample_points_uniformly(number_of_points=5000)
o3d.visualization.draw_geometries([pc], window_name='t')

In [77]:
o3d.visualization.draw_geometries([pc], window_name='t')

In [78]:
pc_clustered = dbscan(pc, False)
#o3d.visualization.draw_geometries([pc_clustered], window_name='t')

[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 0
point cloud has 0 clusters


In [12]:
pc = mesh.sample_points_uniformly(number_of_points=5000)
o3d.visualization.draw_geometries([pc], window_name='t')

In [13]:
ls_cluster =[]
for i in range(20):
    for j in range(5):
        print(i, j)
        ls_cluster.append(dbscan(pc,10**(i-4), 2**j, False))


0 0
[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 5000
point cloud has 5000 clusters
0 1
[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 0
point cloud has 0 clusters
0 2
[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 0
point cloud has 0 clusters
0 3
[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 0
point cloud has 0 clusters
0 4
[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 0
point cloud has 0 clusters
1 0
[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[

In [21]:
o3d.visualization.draw_geometries([ls_cluster[12]], window_name='t')

In [10]:
pc = dbscan(pc,10**(3-4), 10, False)

[Open3D DEBUG] Precompute Neighbours
[Open3D DEBUG] Done Precompute Neighbours
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 14
point cloud has 14 clusters


In [11]:
o3d.visualization.draw_geometries([pc], window_name='t')

# Mesh Topology


In [5]:
np.asarray(mesh.vertices)

array([[ 1.20654202, -1.57696915,  1.99949074],
       [ 1.1950655 , -1.59717941,  1.99949074],
       [ 1.21610451, -1.5622406 ,  1.99949074],
       ...,
       [ 2.03662682,  1.5753597 ,  7.90054607],
       [ 2.03973579,  1.57888794,  7.90506697],
       [ 2.05755806,  1.59246469,  7.92410421]])

In [6]:
triangle_array = np.asarray(mesh.triangles)


In [7]:
triangle_array.histogram()

AttributeError: 'numpy.ndarray' object has no attribute 'histogram'

In [8]:
np.histogram(triangle_array.flatten())

(array([336506, 337247, 336426, 336290, 336041, 336279, 336055, 335510,
        334785, 315013]),
 array([     0. ,  55983.9, 111967.8, 167951.7, 223935.6, 279919.5,
        335903.4, 391887.3, 447871.2, 503855.1, 559839. ]))

In [ ]:
plt.hist(triangle_array.flatten(), bins=len(triangle_array.flatten()))

In [9]:
len(triangle_array.flatten())

3340152

In [14]:
h = np.histogram(triangle_array.flatten(), bins=len(triangle_array.flatten()))

In [18]:
h[0].max()

13

In [7]:
mesh.compute_adjacency_list()

TriangleMesh with 559840 points and 1113384 triangles.

In [13]:
import sklearn.cluster as C

In [15]:
C.SpectralClustering()

SpectralClustering()